geekshop/authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [

    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),

]

geekshop/basketapp/urls.py
from django.urls import path
import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>/', basketapp.basket_remove, name='remove'),
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path
from mainapp import views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include

'''
urlpatterns = [
    # path('admin/', admin.site.urls),
    path('admin/', include('adminapp.urls',namespace='admin')),
    path('', views.index, name='index'),
    path('products/', views.products, name='products'),
    path('products/<int:category_id>/', views.show_category_products, name='categories'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('contact/', views.contact, name='contact'),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('product/<int:pk>', views.product, name='product'),
]
'''

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('admin/', include('adminapp.urls',namespace='admin')),
    path('', views.index, name='index'),
    path('products/', views.products, name='products'),
    path('products/<int:category_id>/', views.show_category_products, name='categories'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('contact/', views.contact, name='contact'),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('product/<int:pk>', views.product, name='product'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/basketapp/models.py
from django.db import models
from django.db.models import Sum
from mainapp.models import Products
from django.conf import settings


# Create your models here.
class Basket(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='basket')
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    product_quantity = models.PositiveIntegerField(verbose_name='количество', default=0)
    created = models.DateTimeField(verbose_name='время', auto_now_add=True)

    def __str__(self):
        return f'{self.user} {self.product}'

    @staticmethod
    def get_quantity(user=None):
        if user is None:
            return {'total_quantity': 0}
        return Basket.objects.filter(user=user).aggregate(total_quantity=Sum('product_quantity'))

    @staticmethod
    def get_sum(user=None):
        if user is None:
            return {'total_sum': 0}

        products = Basket.objects.filter(user=user)
        total_sum = 0
        for product in products:
            total_sum += product.product_quantity * product.product.price
        return {'total_sum': total_sum}

geekshop/basketapp/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from basketapp.models import Basket
from mainapp.models import Products

from django.contrib.auth.decorators import login_required
from django.urls import reverse


# Create your views here.
def basket(request):
    title = 'корзина'
    basket_items = Basket.objects.filter(user=request.user).order_by('product')

    content = {
        'title': title,
        'basket_items': basket_items,
        'total_quantity': Basket.get_quantity(request.user)['total_quantity'],
        'total_cost': Basket.get_sum(request.user)['total_sum'],
    }

    return render(request, 'basketapp/basket.html', content)


@login_required
def basket_add(request, pk):
    if 'login' in request.META.get('HTTP_REFERER'):
        return HttpResponseRedirect(reverse('products:product', args=[pk]))

    product = get_object_or_404(Products, pk=pk)
    basket = Basket.objects.filter(user=request.user, product=product).first()

    if not basket:
        basket = Basket(user=request.user, product=product)

    basket.product_quantity += 1
    basket.save()

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def basket_remove(request, pk):
    basket_record = get_object_or_404(Basket, pk=pk)
    basket_record.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

geekshop/basketapp/templates/basketapp/base.html
<!DOCTYPE html>

{% load static %}

<html>
<head>
	<meta charset="utf-8">
	<title>
        {% block title %}
        {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
	<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
	<link rel="stylesheet" href="% static '/fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>
<body>
	<div class="basket_container">
      <div class="h2 text-center head">
		Ваша корзина
           {% if user.first_name %}
            {{ user.first_name|title }}
           {% else %}
            Пользователь
           {% endif %}
        </div>
        {% block content %}
        {% endblock %}
	</div>
</body>
</html>

geekshop/basketapp/templates/basketapp/basket.html
{% extends 'basketapp/base.html' %}
{% load static %}

{% block content %}
<div class="basket_list">
  <p>{{ len }}</p>
  {% for item in basket_items %}
  <div class="basket_record">
      <img src="/media/{{item.product.image}}" alt="{{ item.product.short_desc }}">
      <span class="category_name">{{ item.product.category.name }}</span>
      <span class="product_name">{{ item.product.name }}</span>
      <span class="category_price">{{ item.product.price }}</span>

      <input type="number" name="{{ item.pk }}" min="0", value="{{ item.product_quantity }}">
      <span class="product_cost">{{ item.cost }} руб.</span>

      <button class="btn btn-round">
        <a href="{% url 'basket:remove' item.pk %}" class=""> Удалить </a>
      </button>
  </div>
  {% endfor %}

  {% if basket_items %}
  <div class="basket_summery">
    В корзине {{ total_quantity }} товаров общей стоимостью
    {{ total_cost }} руб.
  </div>
  {% endif %}


  <button class="btn btn-round">
   <a href="{% url 'index' %}"> На главную страницу </a>
  </button>

</div>
{% endblock %}