geekshop/adminapp/urls.py
import adminapp.views as adminapp
from django.urls import path

app_name = 'adminapp'

urlpatterns = [
    path('user/create/', adminapp.user_create, name='user_create'),
    # path('user/read/', adminapp.users, name='users'),
    path('user/read/', adminapp.UserListView.as_view(), name='users'),
    path('user/update/<int:pk>/', adminapp.user_update, name='user_update'),
    path('user/delete/<int:pk>/', adminapp.user_delete, name='user_delete'),

    # path('categories/create/', adminapp.category_create, name='category_create'),
    path('categories/create/', adminapp.ProductCategoryCreateView.as_view(), name='category_create'),
    path('categories/read/', adminapp.categories, name='categories'),
    # path('categories/update/<int:pk>/', adminapp.category_update, name='category_update'),
    path('categories/update/<int:pk>/', adminapp.ProductCategoryUpdateView.as_view(), name='category_update'),
    # path('categories/delete/<int:pk>/', adminapp.category_delete, name='category_delete'),
    path('categories/delete/<int:pk>/', adminapp.ProductCategoryDeleteView.as_view(), name='category_delete'),

    path('products/create/category/<int:pk>/', adminapp.product_create, name='product_create'),
    path('products/read/category/<int:pk>/', adminapp.products, name='products'),
    path('products/read/<int:pk>/', adminapp.product_read, name='product_read'),
    path('products/update/<int:pk>/', adminapp.product_update, name='product_update'),
    path('products/delete/<int:pk>/', adminapp.product_delete, name='product_delete'),
]

geekshop/authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [

    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),

]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path
from mainapp import views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include

'''
urlpatterns = [
    # path('admin/', admin.site.urls),
    path('admin/', include('adminapp.urls',namespace='admin')),
    path('', views.index, name='index'),
    path('products/', views.products, name='products'),
    path('products/<int:category_id>/', views.show_category_products, name='categories'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('contact/', views.contact, name='contact'),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('product/<int:pk>', views.product, name='product'),
]
'''

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('admin/', include('adminapp.urls',namespace='admin')),
    path('', views.index, name='index'),
    path('products/', views.products, name='products'),
    path('products/<int:category_id>/', views.show_category_products, name='categories'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('contact/', views.contact, name='contact'),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('product/<int:pk>', views.product, name='product'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/adminapp/models.py
from django.db import models

# Create your models here.

geekshop/adminapp/forms.py
from django import forms
from authapp.models import ShopUser
from authapp.forms import ShopUserEditForm
from mainapp.models import ProductCategory, Products



class ShopUserAdminForm(ShopUserEditForm):
    class Meta:
        model = ShopUser
        fields = '__all__'


class ProductCategoryCreateForm(forms.ModelForm):
    class Meta:
        model = ProductCategory
        fields = '__all__'


class ProductCategoryEditForm(forms.ModelForm):
    class Meta:
        model = ProductCategory
        fields = '__all__'

        def __init__(self, *args, **kwargs):
            super(ProductCategoryEditForm).__init__(*args, **kwargs)
            for field_name, field in self.fields.items():
                field.widget.attrs['class'] = 'form-control'
                field.help_text = ''


class ProductEditForm(forms.ModelForm):
    class Meta:
        model = Products
        fields = '__all__'

        def __init__(self, *args, **kwargs):
            super(ProductCategoryEditForm).__init__(*args, **kwargs)
            for field_name, field in self.fields.items():
                field.widget.attrs['class'] = 'form-control'
                field.help_text = ''

geekshop/adminapp/views.py
from django.shortcuts import render, HttpResponseRedirect
from authapp.models import ShopUser
from django.shortcuts import get_object_or_404
from mainapp.models import Products, ProductCategory
from django.contrib.auth.decorators import user_passes_test
from authapp.forms import ShopUserRegisterForm, ShopUserEditForm
from django.urls import reverse, reverse_lazy
from adminapp.forms import ShopUserAdminForm, ProductCategoryEditForm, ProductCategoryCreateForm, ProductEditForm
from django.views.generic.list import ListView
from django.utils.decorators import method_decorator
from django.views.generic.edit import CreateView, UpdateView, DeleteView

# Create your views here.

'''
@user_passes_test(lambda u: u.is_superuser)
def users(request):
    title = 'админка/пользователей'

    user_list = ShopUser.objects.all().order_by('-is_active', '-is_superuser', '-is_staff', 'username')

    content = {
        'title': title,
        'objects': user_list,
    }

    return render(request, 'adminapp/users.html', content)
'''


class UserListView(ListView):
    model = ShopUser
    template_name = 'adminapp/users.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


@user_passes_test(lambda u: u.is_superuser)
def user_create(request):
    title = 'пользователь/создание'

    if request.method == 'POST':
        user_form = ShopUserRegisterForm(request.POST, request.FILES)
        if user_form.is_valid():
            user_form.save()
            return HttpResponseRedirect(reverse('admin:users'))
    else:
        user_form = ShopUserRegisterForm()

    content = {'title': title, 'update_form': user_form}

    return render(request, 'adminapp/user_update.html', content)


@user_passes_test(lambda u: u.is_superuser)
def user_update(request, pk):
    title = 'пользователи/редактирование'

    edit_user = get_object_or_404(ShopUser, pk=pk)
    if request.method == 'POST':
        edit_form = ShopUserAdminForm(request.POST, request.FILES, instance=edit_user)

        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('admin:user_update', args=[edit_user.pk]))
    else:
        edit_form = ShopUserAdminForm(instance=edit_user)

    content = {'title': title, 'update_form': edit_form}

    return render(request, 'adminapp/user_update.html', content)


@user_passes_test(lambda u: u.is_superuser)
def user_delete(request, pk):
    title = 'пользователь/удаление'
    user = get_object_or_404(ShopUser, pk=pk)

    if request.method == 'POST':
        user.is_active = False
        user.save()
        return HttpResponseRedirect(reverse('admin:users'))

    content = {'title': title, 'user_to_delete': user}

    return render(request, 'adminapp/user_delete.html', content)


@user_passes_test(lambda u: u.is_superuser)
def categories(request):
    title = 'админка/категории'

    categories_list = ProductCategory.objects.all()

    content = {
        'title': title,
        'objects': categories_list,
    }

    return render(request, 'adminapp/categories.html', content)


@user_passes_test(lambda u: u.is_superuser)
def category_create(request):
    title = 'категории/создание'

    if request.method == 'POST':
        category_form = ProductCategoryCreateForm(request.POST, request.FILES)
        if category_form.is_valid():
            category_form.save()
            return HttpResponseRedirect(reverse('admin:users'))
    else:
        category_form = ProductCategoryCreateForm()

    content = {'title': title, 'update_form': category_form}

    return render(request, 'adminapp/categories_update.html', content)


@user_passes_test(lambda u: u.is_superuser)
def category_read(request, pk):
    pass


@user_passes_test(lambda u: u.is_superuser)
def category_update(request, pk):
    title = 'категории/редактирование'

    edit_category = get_object_or_404(ProductCategory, pk=pk)
    if request.method == 'POST':
        edit_form = ProductCategoryEditForm(request.POST, request.FILES, instance=edit_category)

        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('admin:category_update', args=[edit_category.pk]))
    else:
        edit_form = ProductCategoryEditForm(instance=edit_category)

    content = {'title': title, 'update_form': edit_form}

    return render(request, 'adminapp/categories_update.html', content)


@user_passes_test(lambda u: u.is_superuser)
def category_delete(request, pk):
    title = 'категория/удаление'
    category = get_object_or_404(ProductCategory, pk=pk)

    if request.method == 'POST':
        category.is_active = False
        category.save()
        return HttpResponseRedirect(reverse('admin:categories'))

    content = {'title': title, 'category_to_delete': category}

    return render(request, 'adminapp/categories_delete.html', content)


@user_passes_test(lambda u: u.is_superuser)
def products(request, pk):
    title = 'админка/продукт'

    category = get_object_or_404(ProductCategory, pk=pk)

    products_list = Products.objects.filter(category__pk=pk).order_by('name')

    content = {
        'title': title,
        'category': category,
        'objects': products_list,
    }

    return render(request, 'adminapp/products.html', content)


class ProductCategoryCreateView(CreateView):
    model = ProductCategory
    template_name = 'adminapp/categories_update.html'
    success_url = reverse_lazy('admin:categories')
    fields = '__all__'


class ProductCategoryUpdateView(UpdateView):
    model = ProductCategory
    template_name = 'adminapp/categories_update.html'
    success_url = reverse_lazy('admin:categories')
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'категории/редактирование'
        return context


class ProductCategoryDeleteView(DeleteView):
    model = ProductCategory
    template_name = 'adminapp/categories_delete.html'
    success_url = reverse_lazy('admin:categories')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()

        return HttpResponseRedirect(self.get_success_url())


@user_passes_test(lambda u: u.is_superuser)
def product_create(request, pk):
    title = 'продукты/создание'
    category = get_object_or_404(ProductCategory, pk=pk)

    if request.method == 'POST':
        product_form = ProductEditForm(request.POST, request.FILES)
        if ProductEditForm.is_valid():
            ProductEditForm.save()
            return HttpResponseRedirect(reverse('admin:products', args=[pk]))
    else:
        product_form = ProductEditForm(initial={'category': category})

    content = {'title': title, 'update_form': product_form, 'category': category}

    return render(request, 'adminapp/product_update.html', content)


@user_passes_test(lambda u: u.is_superuser)
def product_read(request, pk):
    title = 'продукты/подробнее'
    product = get_object_or_404(Products, pk=pk)

    content = {'title': title, 'object': product}

    return render(request, 'adminapp/product_read.html', content)


@user_passes_test(lambda u: u.is_superuser)
def product_update(request, pk):
    title = 'продукты/редактирование'

    edit_product = get_object_or_404(Products, pk=pk)
    if request.method == 'POST':
        edit_form = ProductEditForm(request.POST, request.FILES, instance=edit_product)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('admin:product_update', args=[edit_product.pk]))
    else:
        edit_form = ProductEditForm(instance=edit_product)

    content = {'title': title, 'update_form': edit_form, 'category': edit_product.category}

    return render(request, 'adminapp/product_update.html', content)


@user_passes_test(lambda u: u.is_superuser)
def product_delete(request, pk):
    title = 'продукты/удаление'
    product = get_object_or_404(Products, pk=pk)
    if request.method == 'POST':
        product.is_active = False
        product.save()
        return HttpResponseRedirect(reverse('admin:products', args=[product.category.pk]))

    content = {'title': title, 'product_to_delete': product}

    return render(request, 'adminapp/product_delete.html', content)

geekshop/adminapp/templates/adminapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Административная часть сайта</title>
</head>
<body>
<div class="admin_container">
  <div class="h2 text-center head">
    Админка
  </div>
  {% block menu %}
  <div class="admin_menu">
    {% include 'adminapp/includes/inc_menu.html' %}
  </div>
  {% endblock %}

  {% block content %}

  {% endblock %}
</div>
</body>
</html>

geekshop/adminapp/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<div class="categories_list">
  <button class="new_category">
    <a href="{% url 'admin:category_create' %}">
      Новая категория
    </a>
  </button>

  {% for object in objects %}
  <div class="category_record
    {% if not objects.is_active %}
      not_active
    {% endif %}">
    <div class="category_name">
      {{ object.name|title }}
    </div>
    <div class="category_actions">
      <button>
        <a href="{% url 'admin:products' object.pk %}">
          Товары категории
        </a>
      </button>
      <button>
        <a href="{% url 'admin:category_update' object.pk %}">
          Редактировать
        </a>
      </button>
       <button>
        <a href="{% url 'admin:category_delete' object.pk %}">
          Удалить
        </a>
      </button>
    </div>
    <div class="category_desc">
      {{ object.description|title }}
    </div>
  </div>
  {% endfor %}

</div>
{% endblock %}

geekshop/adminapp/templates/adminapp/categories_delete.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}
<div class="user_delete">
  Уверены, что хотите удалить {{ category_to_delete.name }}?
  <form action="{% url 'admin:category_delete' category_to_delete.pk %}" method="post">
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="удалить">
  </form>
  <button class="btn btn-success">
    <a href="{% url 'admin:categories' %}">
      Отмена
    </a>
  </button>
</div>
{% endblock %}

geekshop/adminapp/templates/adminapp/categories_delete_copy.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<div class="user_delete">
  Уверены, что хотите удалить {{ category_to_delete.name }}?
  <form action="{% url 'admin:category_delete' category_to_delete.pk %}" method="post">
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="удалить">
  </form>
  <button class="btn btn-success">
    <a href="{% url 'admin:categories' category_to_delete.pk %}">
      Отмена
    </a>
  </button>
</div>
{% endblock %}

geekshop/adminapp/templates/adminapp/categories_update.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}
<form class="form-horizontal" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ update_form.as_p }}
  <input class="form-control" type="submit" value="сохранить">
</form>
<button class="btn btn-round form-control last">
  <a href="{% url 'admin:categories' %}">
    к списку категорий
  </a>
</button>
{% endblock %}</html>

geekshop/adminapp/templates/adminapp/categories_update_copy.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<form class="form-horizontal" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ update_form.as_p }}
  <input class="form-control" type="submit" value="сохранить">
</form>
<button class="btn btn-round form-control last">
  <a href="{% url 'admin:categories' %}">
    к списку категорий
  </a>
</button>
{% endblock %}</html>

geekshop/adminapp/templates/adminapp/product_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<div class="product_delete">
  Уверены, что хотите удалить {{ product_to_delete.name }}?
  <form action="{% url 'admin:product_delete' product_to_delete.pk %}" method="post">
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="удалить">
  </form>
  <button class="btn btn-success">
    <a href="{% url 'admin:products' product_to_delete.category.pk %}">
      Отмена
    </a>
  </button>
</div>
{% endblock %}l>

geekshop/adminapp/templates/adminapp/product_read.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<div class="product_read">
    <div class="product_name">
        Продукт <strong>{{ object.category.name|title }} / {{ object.name|title }}</strong>
    </div>
    <img src="/media/{{ object.image|default:'products_images/default.jpg' }}" alt="{{ object.name }}">
    <div class="summary">
        <b>цена</b>
        <p>{{ object.price }}</p>
        <b>количество</b>
        <p>{{ object.quantity }}</p>
        <b>в каталоге</b>
        <p>{% if object.is_active %}да{% else %}нет{% endif %}</p>
        <p>
            <button>
                <a href="{% url 'admin:product_update' object.pk %}">
                    редактировать
                </a>
            </button>
        </p>
        <p>
        <button>
            <a href="{% url 'admin:product_delete' object.pk %}">
                удалить
            </a>
        </button>
        </p>
        <p>
            <button>
                <a href="{% url 'admin:products' object.category.pk %}">
                    назад
                </a>
            </button>
        </p>
    </div>
    <div class="product_desc">
        <b>краткая информация</b>
        <p>{{ object.short_desc }}</p>
        <b>подробная информация</b>
        <p>{{ object.description }}</p>
    </div>
</div>
{% endblock %}

geekshop/adminapp/templates/adminapp/products.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<div class="product_list">
  <button class="new_product">
    <a href="{% url 'admin:product_create' category.pk %}">
      Новый продукт
    </a>
  </button>

  {% for object in objects %}
  <div class="product_record">
    <img src="/media/{{ object.image|default:'products_images/default.jpg' }}" alt="{{ object.name }}">
  </div>
  <div class="product_name">
    {{ object.name|title }}
  </div>
  <div class="product_actions">
    <button>
      <a href="{% url 'admin:product_read' object.pk %}">
        Подробнее
      </a>
    </button>
    <button>
      <a href="{% url 'admin:product_update' object.pk %}">
        Редактировать
      </a>
    </button>
    <button>
      <a href="{% url 'admin:product_delete' object.pk %}">
        Удалить
      </a>
    </button>
  </div>
  <div class="summary">
    <b>Цена</b>
    <p>{{ object.price }} руб. </p>
    <b>Количество</b>
    <p>{{ object.short_desc|title }}</p>
  </div>
  {% endfor %}
</div>
{% endblock %}

geekshop/adminapp/templates/adminapp/user_delete.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}
<div class="user_delete">
  Уверены, что хотите удалить {{ user_to_delete.username }}
  {% if user_to_delete.first_name %}
  ({{ user_to_delete.first_name|title }}
  {% if user_to_delete.last_name %}
  {{ user_to_delete.last_name|title }}
  {% endif %}
  {% endif %}
  )?
  <form action="{% url 'admin:user_delete' user_to_delete.pk %}" method="post">
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="удалить">
  </form>
  <button class="btn btn-success">
    <a href="{% url 'admin:users' %}">
      Отмена
    </a>
  </button>
</div>
{% endblock %}

geekshop/adminapp/templates/adminapp/user_update.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}
<form class="form-horizontal" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ update_form.as_p }}
  <input class="form-control" type="submit" value="сохранить">
</form>
<button class="btn btn-round form-control last">
  <a href="{% url 'admin:users' %}">
    к списку пользователей
  </a>
</button>
{% endblock %}

geekshop/adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<div class="user_list">
  <button class="new_user">
    <a href="{% url 'admin:user_create' %}">Новый пользователь</a>
  </button>
  {% for object in object_list %}
  <div class="user_record {% if not object.is_active %} not_active {% endif %}">
    <img src="/media/{{ object.avatar|default:'users_avatar/default.jpg' }}" alt="{{ object.username }}">
    <div class="user_role">
      {% if object.is_superuser %}
      Администратор
      {% else %}
      Пользователь
      {% endif %}
      <button>
        <a href="{% url 'admin:user_update' object.pk %}">
          Редактирование
        </a>
      </button>
      <button>
        <a href="{% url 'admin:user_delete' object.pk %}">
          Удалить
        </a>
      </button>
    </div>
    <div class="user_name">
      <p><strong>{{ object.name }}</strong></p>
      <p>
        {% if object.first_name %}
        <b>{{ object.first_name|title }}</b>
        {% endif %}
        {% if object.last_name %}
       <b>{{ object.last_name|title }}</b>
       {% endif %}
      </p>
    </div>
    <div class="user_age">
      age:<br>
      {{ object.age }} лет
    </div>
    <div class="user_email">
      email:<br>
      {{ object.email }}
    </div>
    <div class="user_lastlogin">
      logged:<br>
      {{ object.last_login }}
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}