geekshop/authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [

    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),

]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path
from mainapp import views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include

'''
urlpatterns = [
    # path('admin/', admin.site.urls),
    path('admin/', include('adminapp.urls',namespace='admin')),
    path('', views.index, name='index'),
    path('products/', views.products, name='products'),
    path('products/<int:category_id>/', views.show_category_products, name='categories'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('contact/', views.contact, name='contact'),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('product/<int:pk>', views.product, name='product'),
]
'''

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('admin/', include('adminapp.urls',namespace='admin')),
    path('', views.index, name='index'),
    path('products/', views.products, name='products'),
    path('products/<int:category_id>/', views.show_category_products, name='categories'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('contact/', views.contact, name='contact'),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('product/<int:pk>', views.product, name='product'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/authapp/models.py
from django.db import models

from django.contrib.auth.models import User, AbstractUser


# Create your models here.

class ShopUser(AbstractUser):
    age = models.PositiveSmallIntegerField(verbose_name='возраст', null=True)
    avatar = models.ImageField(upload_to='users_avatars', blank=True)

geekshop/authapp/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserChangeForm
from django.contrib.auth.forms import UserCreationForm
from django import forms

from .models import ShopUser


class ShopUserLoginForm(AuthenticationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(ShopUserLoginForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ShopUserRegisterForm(UserCreationForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'password1', 'password2', 'email', 'age', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError('Вы слишком молоды для регистрации')
        return data


class ShopUserEditForm(UserChangeForm):
    class Meta:
        model = ShopUser
        fields = ('username', 'first_name', 'password', 'email', 'age', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''
            # if field_name == 'password':
            #    field.widget = forms.HiddenInput()
            self.fields['password'].widget = forms.HiddenInput()

    def clean_age(self):
        data = self.cleaned_data['age']
        if data < 18:
            raise forms.ValidationError('Вы слишком молоды для регистрации')
        return data

geekshop/authapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, HttpResponseRedirect
from django.contrib import auth
from authapp.forms import ShopUserLoginForm, ShopUserRegisterForm, ShopUserEditForm
from django.urls import reverse


# Create your views here.

def login(request):
    title = 'вход'
    login_form = ShopUserLoginForm(data=request.POST)

    # next = request.GET['next'] if 'next' in request.GET.key() else ''

    if request.method == 'POST' and login_form.is_valid():
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)
        if user and user.is_active:
            auth.login(request, user)
            # if 'next' in request.POST.key():
            #    return HttpResponseRedirect(request.POST['next'])
            # else:
            #    return HttpResponseRedirect('/')

    content = {'title': title,
               'login_form': login_form,
               'next': next,
               }
    return render(request, 'authapp/login.html', content)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect('/')


def register(request):
    title = 'регистрация'
    if request.method == 'POST':
        register_form = ShopUserRegisterForm(request.POST, request.FILES)

        if register_form.is_valid():
            register_form.save()
            return HttpResponseRedirect(reverse('auth:login'))
    else:
        register_form = ShopUserRegisterForm()
    content = {'title': title, 'register_form': register_form}
    return render(request, 'authapp/register.html', content)


def edit(request):
    title = 'редактирование'

    if request.method == 'POST':
        edit_form = ShopUserEditForm(request.POST, request.FILES, instance=request.user)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('auth:edit'))
    else:
        edit_form = ShopUserEditForm(instance=request.user)

    content = {'title': title, 'edit_form': edit_form}
    return render(request, 'authapp/edit.html', content)

geekshop/authapp/templates/authapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
      {% block title %}
        {{ title|title }}
      {% endblock %}
    </title>
    {% block css %}
<!--      <link rel="stylesheet" type="text/css" href="#">-->
    {% endblock %}
</head>
<body>
<div class="container">
  <div class="login">
    <div class="h2 text-center head">
      Вход в систему
    </div>
    {% block content %}
    {% endblock %}
  </div>
</div>

</body>
</html>

geekshop/authapp/templates/authapp/edit.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}
<form class="form-horizontal" action="{% url 'auth:edit' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ edit_form.as_p }}
    <input class="form-control" type="submit" value="Сохранить">
</form>
<button class="btn btn-round form-control last">
    <a href="{% url 'index' %}" class="">
        На главную
    </a>
</button>
<div class="user-avatar"><img src="/media/{{ user.avatar }}"></div>
{% endblock %}

geekshop/authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}

<form class="form-horizontal" action="{% url 'auth:login' %}" method="post">
    {% csrf_token %}
    {{ login_form.as_p }}
    <br>
    <input class="form-control" type="submit" value="Войти">
</form>

{% endblock %}

geekshop/authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}

<form class="form-horizontal" action="{% url 'auth:register' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ register_form.as_p }}
    <input class="form-control" type="submit" value="Зарегистрироваться">
</form>

{% endblock %}