geekshop/authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [

    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),

]

geekshop/basketapp/urls.py
from django.urls import path
import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>/', basketapp.basket_remove, name='remove'),
]

geekshop/geekshop/urls.py
from django.contrib import admin
from django.urls import path
from mainapp import views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include

'''
urlpatterns = [
    # path('admin/', admin.site.urls),
    path('admin/', include('adminapp.urls',namespace='admin')),
    path('', views.index, name='index'),
    path('products/', views.products, name='products'),
    path('products/<int:category_id>/', views.show_category_products, name='categories'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('contact/', views.contact, name='contact'),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('product/<int:pk>', views.product, name='product'),
]
'''

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('admin/', include('adminapp.urls',namespace='admin')),
    path('', views.index, name='index'),
    path('products/', views.products, name='products'),
    path('products/<int:category_id>/', views.show_category_products, name='categories'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('contact/', views.contact, name='contact'),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('product/<int:pk>', views.product, name='product'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

geekshop/mainapp/models.py
from django.db import models

# Create your models here.
class ProductCategory(models.Model):

    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    descriptions = models.TextField(verbose_name='описание', blank=True)
    is_active = models.BooleanField(verbose_name='активно', default=True)

    def __str__(self):
        return self.name


class Products(models.Model):

    category = models.ForeignKey(ProductCategory, on_delete = models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=64)
    image = models.ImageField(upload_to = 'products_images', blank = True)
    image_1 = models.ImageField(upload_to='products_images', blank=True)
    image_2 = models.ImageField(upload_to='products_images', blank=True)
    image_3 = models.ImageField(upload_to='products_images', blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    is_active = models.BooleanField(verbose_name='активно', default=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits = 15, decimal_places = 2, default = 0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default = 0)

    def __str__(self):
        return f'{self.name} ({self.category.name} {self.image})'

geekshop/mainapp/views.py
from django.shortcuts import render, get_object_or_404
from django.conf import settings  # В настройках пропишем путь до файла products.json
import json  # модуль для преобразования текста в json и затем в словарь
import \
    os  # надо определить абсолютный путь к файлу products.json (через относительный не понимает. Говорит нет такого файла.).
# Для этого в settings.py добавил путь FILE_PRODUCTS

from basketapp.views import Basket

from mainapp.models import ProductCategory, Products
import random
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.
main_menu = [
    {'href': 'index', 'name': 'домой'},
    {'href': 'products', 'name': 'продукты'},
    {'href': 'contact', 'name': 'контакты'},
]

'''
links_menu = [
    {'href': 'products_all', 'name': 'все'},
    {'href': 'product_home', 'name': 'дом'},
    {'href': 'product_office', 'name': 'офис'},
    {'href': 'product_modern', 'name': 'модерн'},
    {'href': 'product_classic', 'name': 'классика'},
]
'''


def index(request):
    context = {
        'title': 'Магазин',
        'main_menu': main_menu,
    }

    return render(request, 'mainapp/index.html', context)


def products(request):
    links_menu = ProductCategory.objects.all().order_by('name')
    # all_products = Products.objects.all()
    all_products = Products.objects.filter(is_active=True)
    hot_product = get_hot_product()

    basket = []

    total_quantity = 0
    total_sum = 0

    if request.user.is_authenticated:
        # basket = Basket.objects.filter(user=request.user)
        total_quantity = Basket.get_quantity(request.user)['total_quantity']
        total_sum = Basket.get_sum(request.user)['total_sum']

        content = {
        'main_menu': main_menu,
        'links_menu': links_menu,
        'products': all_products,
        'hot_product': hot_product,
        'total_quantity': total_quantity,
        'total_sum': total_sum,
    }

    return render(request, 'mainapp/products.html', context=content)


def get_hot_product():
    products = Products.objects.all()
    return random.sample(list(products), 1)[0]


def get_same_products(hot_product):
    return Products.objects.filter(category=hot_product.category).exclude(pk=hot_product.pk)[:3]


def contact(request):
    context = {
        'main_menu': main_menu,
    }

    return render(request, 'mainapp/contact.html', context)


def show_category_products(request, category_id=None):

    page = request.GET['page']

    links_menu = ProductCategory.objects.all().order_by('name')

    if category_id in (3, None):  # пока привяжимся к id категории "ВСЕ"
        all_products = Products.objects.all()
    else:
        all_products = Products.objects.filter(category=category_id)

    hot_product = get_hot_product()
    active_category = get_object_or_404(ProductCategory, pk=category_id)

    paginator = Paginator(all_products, 2)

    try:
        products_paginator = paginator.page(page)
    except PageNotAnInteger:
        products_paginator = paginator.page(1)
    except EmptyPage:
        products_paginator = paginator.page(paginator.num_pages)

    context = {
        'main_menu': main_menu,
        'links_menu': links_menu,
        # 'products': all_products,
        'products': products_paginator,
        'active_category_id': category_id,  # передаем для установки активного класса - active
        'hot_product': hot_product,
        'active_category': active_category,
        'page': page
    }

    # return render(request, 'mainapp/products.html', context=context)
    return render(request, 'mainapp/products_list.html', context=context)


def get_products():
    filename = os.path.join(settings.FILE_PRODUCTS, 'products.json')

    with open(filename, 'r', encoding='utf-8') as f:
        data = json.loads(f.read().replace("'", '"'))
    return data


def get_basket(user):
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    else:
        return []


def product(request, pk):
    title = 'продукты'
    links_menu = ProductCategory.objects.all().order_by('name')

    content = {
        'title': title,
        'links_menu': links_menu,
        'product': get_object_or_404(Products, pk=pk),
        'basket': get_basket(request.user),
    }

    return render(request, 'mainapp/product.html', content)

geekshop/mainapp/templates/mainapp/Base.html
{% load static %}
{% load my_tags %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>
        {% block title %}
        {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
	<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
	<link rel="stylesheet" href="% static '/fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>
<body>
	<div class="container">
		{% block menu %}
        {% endblock %}
        {% block content %}
        {% endblock %}

		<div class="clr"></div>

	</div>

    {% block footer %}
    <div class="footer">
        <div class="clearfix">
            <div class="text-footer">
                <h3>контакты</h3>
            </div>
            <div class="text-footer">
                <h3>полезная информация</h3>
            </div>
            <div class="text-footer clearfix">
                <h3>Оставайтесь на связи</h3>
                <p>Подписаться на новости и рассылки</p>
                <form>
                    <input type="email" name="email" placeholder="ваш email">
                    <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                </form>
            </div>
        </div>
        <p class="small">&copy; GB {% now "Y" %}</p>
        <div class="social">
            <a href="#" class="social1"></a>
            <a href="#" class="social2"></a>
            <a href="#" class="social3"></a>
            <a href="#" class="social4"></a>
        </div>
        <p class="small">Положения &amp; Условия  /  Конфиденциальность &amp; Cookies</p>
    </div>
    {% endblock %}

</body>
</html>

geekshop/mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Контакты</title>
</head>
<body>
	<div class="container">

		{% block menu %}
		<div class="hero">
			<div class="header clearfix">
				<a href="index.html" class="logo"></a>
				<ul class="menu">
					<li><a href="{% url 'index' %}">домой</a></li>
					<li><a href="{% url 'products' %}">продукты</a></li>
					<li><a href="{% url 'contact' %}" class="active">контакты</a></li>
				</ul>
				<a href="#" class="search"></a>
                <a href="#" class="basket"></a>
			</div>
			<h1>наши контакты</h1>
		</div>
		{% endblock %}

		{% block content %}
		<div class="location">
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
			<div class="location-1">
				<i class="fa fa-map-marker fa-5x"></i>
				<h4>Москва</h4>
				<div class="contacts">
					<h5>Телефон</h5>
					<p>+7-888-888-8888</p>
				</div>
				<div class="contacts">
					<h5>Email</h5>
					<p>info@geekshop.ru</p>
				</div>
				<div class="contacts">
					<h5>Адрес</h5>
					<p>В пределах МКАД</p>
				</div>
			</div>
		</div>
		{% endblock %}

		<div class="clr"></div>
	</div>
			
</body>
</html>

geekshop/mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">

<!--	<title>{% block title %} {{ title }} {% endblock %}</title>-->

</head>
<body>
	<div class="container">

		{% block menu %}
		<div class="slider">
			<div class="header clearfix">
				<a href="index.html" class="logo"></a>
				{% include 'mainapp/includes/inc_main_menu.html' %}
				<a href="#" class="search"></a>
			</div>
			<div class="text-slider">
				<h3 class="green">тенденции</h3>
				<h3 class="big"> удобные стулья</h3>
				<p>Новый уровень комфорта. Отличные характеристики.</p>
				<a href="#" class="button-order">заказать <img src="{% static 'img/arrow.png' %}" alt=""></a>
			</div>	
			<div class="navi">
				<a href="#"></a><a href="#"></a><a href="#"></a>
			</div>
		</div>
		{% endblock %}

		{% block content %}
		<div class="featured">
			<div class="featured-menu">
					<a class="active" href="#">Популярные</a><a href="#">Новинки</a>
			</div>
			<a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
			<div class="clearfix">
			</div>
			<div class="tab-content">
				<div class="block">
					<a href="#"><img src="{% static 'img/product-1.jpg' %}" alt="">
						<div class="text">
							<img src="{% static 'img/icon-hover.png' %}" alt="img">
							<h4>Отличный стул</h4>
							<p>Расположитесь комфортно. </p>
						</div> 
					</a>
				</div>
				<div class="block">
					<a href="#"><img src="{% static 'img/product-2.jpg' %}" alt="">
						<div class="text">
							<img src="{% static 'img/icon-hover.png' %}" alt="">
							<h4>Стул повышенного качества</h4>
							<p>Не оторваться. </p>
						</div>
					</a>
				</div>	
			</div>
		</div>
		{% endblock %}

		<div class="clr"></div>

	</div>

</body>
</html>

geekshop/mainapp/templates/mainapp/product.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
<div class="details">
  <div class="links clearfix">
    {% include 'mainapp/includes/inc_categories_menu.html' %}
    <ul>
      <li>
        <a href="{% url 'basket:view' %}"> Корзина </a>
      </li>
    </ul>
  </div>
 <div class="details-products">
   <div class="details-slider">
     <div class="slider-product">
       <img src="/media/{{ product.image }}"  width="370px">
     </div>
     <div class="slider-control">
       <div class="block">
         <a href="#"><img src="/media/{{ product.image_1 }}" alt="Картинка 1">
           <div class="text">

           </div>
         </a>
       </div>
       <div class="block">
         <a href="#"><img src="/media/{{ product.image_2 }}" alt="Картинка 2">
           <div class="text">

           </div>
         </a>
       </div>
       <div class="block">
         <a href="#"><img src="/media/{{ product.image_3 }}" alt="Картинка 3">
           <div class="text">

           </div>
         </a>
       </div>
     </div>
   </div>
   <div class="description">
     <h3 class="big-bold">{{ product.name }}</h3>
     <h3 class="red"></h3>
     <p class="price">{{ product.price }}<span>руб</span></p>
     <a href="#" class="red-button">
       заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
     </a>

     <div class="description-text">
       <p>{{ product.description }}</p>
     </div>
     <button>
       <a href="{% url 'basket:add' product.pk %}"> В корзину </a>
     </button>

   </div>
 </div>
</div>
{% endblock %}

geekshop/mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load static %}

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">
<head>
	<meta charset="utf-8">
	<title>Каталог</title>
</head>
<body>
	<div class="container">

		{% block menu %}
		<div class="hero-white">
			<div class="header clearfix">
				<a href="index.html" class="logo"></a>
				{% include 'mainapp/includes/inc_main_menu.html' %}
				<a href="#" class="search"></a>
                <a href="#" class="basket"></a>
			</div>
		</div>
		{% endblock %}

		{% block content %}
		<div class="details">
			<div class="links clearfix">
				{% include 'mainapp/includes/inc_categories_menu.html' %}
			</div>

			<div class="details-products">
				<div class="details-slider">
					<div class="slider-product">
						<img src="/media/{{ hot_product.image }}"  width="370px">
					</div>
					<div class="slider-control">
						<div class="block">
							<a href="#"><img src="/media/{{ hot_product.image_1 }}" alt="Картинка 1">
								<div class="text"></div>
							</a>
						</div>
						<div class="block">
							<a href="#"><img src="/media/{{ hot_product.image_2 }}" alt="Картинка 2">
								<div class="text"></div>
							</a>
						</div>
						<div class="block">
							<a href="#"><img src="/media/{{ hot_product.image_3 }}" alt="Картинка 3">
								<div class="text"></div>
							</a>
						</div>
					</div>
				</div>

				<div class="description">
					<h3 class="big-bold">{{ hot_product.name }}</h3>
					<h3 class="red">горячее предложение</h3>
					<h3 class="red"></h3>
					<p class="price">{{ hot_product.price }}<span>руб</span></p>
					<a href="#" class="red-button">
						заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
					</a>

					<div class="description-text">
						<p>{{ hot_product.description }}</p>
					</div>

				</div>
			</div>

			<div class="related">
				<div class="title clearfix">
					<h2>Похожие продукты</h2>
					<a class="explore" href="#">показать все <img src="{% static 'img/arrow.png' %}" alt=""></a>
				</div>
				<div class="related-products clearfix">

					{% for product in products %}

					<div class="block">
						<a href="{% url 'product' product.pk %}"><img src="/media/{{ product.image }}" width="370px" height="370px" alt="картинка товара">
							<div class="text">
								<img src="{% static 'img/icon-hover.png' %}" alt="img">
								<h4>{{ product.name }}</h4>
								<p>{{ product.description }}</p>
							</div>
						</a>
					</div>

					{% endfor %}

				</div>
			</div>
		</div>
		{% endblock %}

		<div class="clr"></div>

	</div>	

</body>
</html>

geekshop/mainapp/templates/mainapp/products_list.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
<div class="links clearfix">
    <ul class="links-menu">
         <li>
             <a href = "{% url 'products' %}">На страницу продуктов</a>
         </li>
        <li>
             <a>{% if active_category_id == 3 %}Все категории{% else %}{{ active_category.name }}{% endif %}</a>
        </li>
    </ul>

  <div class="paginator">
    {% if products.has_previous %}
    <a href="?page={{ products.previous_page_number }}">
        <
    </a>
    {% endif %}
    <span class="current">
      страница {{ products.number }} из {{ products.paginator.num_pages }}
    </span>
    {% if products.has_next %}
    <a href="?page={{ products.next_page_number }}">
        >
    </a>
    {% endif %}
  </div>
</div>

{% for product in products %}
<div class="related-products clearfix">
<div class="block">
  <a href="{% url 'product' product.pk %}"><img src="/media/{{ product.image }}" width="370px" height="370px" alt="картинка товара">
    <div class="text">
      <img src="{% static 'img/icon-hover.png' %}" alt="img">
      <h4>{{ product.name }}</h4>
      <p>{{ product.description }}</p>
    </div>
  </a>
</div>
</div>
{% endfor %}
{% endblock %}